name: Mypy

on:
  push:
    branches:
      - main
      - ForWork
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main, ForWork]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Create mypy cache directory
        run: mkdir -p .mypy_cache/
      - name: Analysing the code with mypy
        run: |
          mypy --config-file mypy.ini .
