name: Pylint

on:
  push:
    branches:
      - main
      - ForWork
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main, ForWork]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint --disable=C0103,R0903,R0801,E0401,C0114,C0116,R1705,W0719,C0411,C0412,C0115,W0201,W0621,W0246,R0913,R0801,W3101,W0613,W1203 **/*.py
